### PR TITLE
Add server constructor with ApplicationEngineEnvironment

### PR DESCRIPTION
**Pull request by Atternatt**
This PR tries to solve the need for ssl configuration (or any other that can by done through `ApplicationEngineEnvironment`) in Ktor Server using suspendapp

### CODE REVIEW

**Review by nomisRev — APPROVED** [review]
Looks perfect! Thank you @Atternatt!! 👏 👏

**Comment by nomisRev** [comment]
@Atternatt, I think you were missing a `apiDump` and perhaps a `spotlessApply`.

**Comment by Atternatt** [comment]
@nomisRev sure, I'm in a road trip and I'm developing in the free time while not driving. will do it as soon as I can reach the laptop 😁

**Comment by nomisRev** [comment]
@Atternatt whenever I comment it's not to rush you 😅 No worries about that!
Be safe, and enjoy your road trip! 🌴

**Pull request merged**
